### PR TITLE
feat(grid): add strictAutoFit option

### LINKED ISSUE #2390: [Bug Report] FormGrid  的 maxWidth 参数无效
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/laughing-bohr-tun6z?file=/App.tsx)

### Steps to reproduce

1. 打开 Codesandbox
2. F12 打开控制台查看元素的尺寸

### What is expected?
GridItem  的最大宽度不要超过 120px

### What is actually happening?
GridItem 的尺寸可以突破设定的 maxWidth

### Package
@formily/grid@2.0.0-rc.17

---

### PR DESCRIPTION
**Pull request by liuweiGL**
_Before_ submitting a pull request, please make sure the following is done...

- [x] Ensure the pull request title and commit message follow the [Commit Specific](https://github.com/alibaba/formily/blob/formily_next/.github/GIT_COMMIT_SPECIFIC.md) in **English**.
- [x] Fork the repo and create your branch from `master` or `formily_next`.
- [x] If you've added code that should be tested, add tests!
- [x] If you've changed APIs, update the documentation.
- [x] Ensure the test suite passes (`npm test`).
- [x] Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.

**Please do not delete the above content**

close #2390
---

### CODE REVIEW

**Comment by janryWang** [comment]
strictAutoFit默认应该是false吧

**Comment by liuweiGL** [comment]
> strictAutoFit默认应该是false吧

改变当前行为你那边不会受影响吗？

**Comment by janryWang** [comment]
> > strictAutoFit默认应该是false吧
> 
> 改变当前行为你那边不会受影响吗？

默认为false就不会

**Comment by liuweiGL** [comment]
不对呀，strictAutoFit 默认为 false 就不会走之前的逻辑了呢：
```ts
    this.options = {
      breakpoints: [720, 1280, 1920],
      columnGap: 8,
      rowGap: 4,
      minWidth: 100,
      colWrap: true,
      strictAutoFit: false, 
      ...options,
    }
```

```ts
    if (this.options.strictAutoFit !== false) {
      const columnWidth =
        (this.width - (this.columns - 1) * this.columnGap) / this.columns
      if (columnWidth < this.minWidth || columnWidth > this.maxWidth) {
        return `repeat(${this.columns},1fr)`
      }
    }
```

**Comment by liuweiGL** [comment]
现在的逻辑是：用户没传递 strictAutoFit 属性时 strictAutoFit = undefined，还是按照调整之前的逻辑设置 item 为 `1fr`。

**Pull request merged**
