### PR TITLE
fix(shared): fix ReDos

### PR DESCRIPTION
**Pull request by ready-research**
_Before_ submitting a pull request, please make sure the following is done...

- [X] Ensure the pull request title and commit message follow the [Commit Specific](https://github.com/alibaba/formily/blob/formily_next/.github/GIT_COMMIT_SPECIFIC.md) in **English**.
- [X] Fork the repo and create your branch from `master` or `formily_next`.
- [ ] If you've added code that should be tested, add tests!
- [ ] If you've changed APIs, update the documentation.
- [ ] Ensure the test suite passes (`npm test`).
- [ ] Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.

## What have you changed?
Fix potential ReDoS
Access the report https://www.huntr.dev/bounties/aa00a9eb-1da6-4e7d-9fdb-de3ea0917def/ using your GitHub on the top right corner of huntr page. If you are able to access then you can just click on `mark as valid` and also you can `confirm the fix`.

### CODE REVIEW

**Comment by janryWang** [comment]
Fix ReDoS need modify to fix ReDos

**Comment by janryWang** [comment]
bugfix(shared) ==> fix(shared)

**Comment by ready-research** [comment]
Hi team,

I am not sure what is the issue here. Can any of the contributors edit this PR or raise a new one with my patch to resolve this issue? 
And please validate this [huntr](https://www.huntr.dev/bounties/aa00a9eb-1da6-4e7d-9fdb-de3ea0917def/) link by using `mark as valid` and also `confirm the fix`.

Thank you.

**Comment by janryWang** [comment]
could you add  some test cases?

**Pull request closed without merging**
